name: nav_care_user_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.1
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  visibility_detector: ^0.4.0+1
  get_it: ^7.7.0
  go_router: ^14.2.1
  easy_localization: ^3.0.7
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.2
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.8
  cross_file: ^0.3.4
  salomon_bottom_bar: ^3.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.2
  feedback: ^3.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  phosphor_flutter: ^2.1.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/env/.env.development
    - assets/env/.env.production
    - assets/images/shell/
    - assets/images/ads/
    - assets/images/services/
    - assets/images/fake/profile_pics/
    - assets/images/fake/hospitals/
    - assets/images/fake/services/
    - assets/images/appointment/
    - assets/error/
    - assets/icon.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
